version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8129:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/horilla"
    command: ./entrypoint.sh
    volumes:
      - ./horilla:/app/horilla
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared_ng

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: horilla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 127.0.0.1:5282:5432
    restart: unless-stopped
    volumes:
      - ./horilla-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_ng
volumes:
  horilla-data:

networks:
  shared_ng:
    name: shared_ng
